// Raincoat — init: generate an example .raincoat.toml and write it out.
#include "init.hpp"

#include <fstream>
#include <sys/stat.h>

namespace raincoat {

std::string default_toml() {
    return
        "# Raincoat configuration profile.\n"
        "# Generated by `raincoat init`. CLI flags override these values.\n"
        "\n"
        "# Run in strict mode? (deny CWD access unless explicitly allowed)\n"
        "strict = false\n"
        "\n"
        "# Network mode: \"full\" (normal host networking) or \"off\" (no network).\n"
        "network = \"full\"\n"
        "\n"
        "# Paths mounted read-only inside the sandbox.\n"
        "allow_read = [\"./src\"]\n"
        "\n"
        "# Paths mounted read-write inside the sandbox.\n"
        "allow_write = [\"./out\"]\n"
        "\n"
        "# Environment variables copied verbatim from the parent (if present).\n"
        "allow_env = [\"OPENAI_API_KEY\"]\n"
        "\n"
        "# Synthetic locale/timezone handed to the sandboxed command.\n"
        "[env]\n"
        "TZ = \"UTC\"\n"
        "LANG = \"en_US.UTF-8\"\n"
        "LC_ALL = \"en_US.UTF-8\"\n"
        "\n"
        "# Best-effort font-fingerprint isolation.\n"
        "[fontconfig]\n"
        "enabled = true\n"
        "\n"
        "# Where the human-readable audit log is written.\n"
        "[audit]\n"
        "log_file = \".raincoat/audit.log\"\n";
}

namespace {
bool file_exists(const std::string& path) {
    struct stat st{};
    return ::stat(path.c_str(), &st) == 0;
}
}  // namespace

bool write_init(const std::string& path, bool force, std::string& err) {
    err.clear();

    if (!force && file_exists(path)) {
        err = "Error: refusing to overwrite existing file: " + path +
              " (re-run with `raincoat init --force` to overwrite it)";
        return false;
    }

    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (!out) {
        err = "Error: could not open file for writing: " + path;
        return false;
    }

    const std::string content = default_toml();
    out << content;
    out.flush();
    if (!out) {
        err = "Error: failed to write file: " + path;
        return false;
    }

    return true;
}

}  // namespace raincoat
